services:
  - type: web
    name: ai-back
    env: python
    plan: free
    pythonVersion: 3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
