services:
  - type: web
    name: ai-back
    env: python
    plan: free
    pythonVersion: 3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
